version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:313830654669:task-definition/aws-auditmanagement-authorization-microservice:2"
        LoadBalancerInfo:
          ContainerName: "aws-auditmanagement-authorization-microservice"
          ContainerPort: 80
        PlatformVersion: "LATEST"